### ISSUE TITLE
Question about the 4 different kernels used for test

### ISSUE THREAD

**Issue by haydenhs** [JiangtaoNie/UAL#5]
Hello Jiangtao,  thanks for sharing your code. I've been trying to re-implement UAL but I could not find the kernels K_1 to K_4 used when testing that are visualized in your paper. It seems that the provided codes only produce Gaussian kernels and box kernels. Could you please share detailed parameters for these 4 kernels?

**Comment by JiangtaoNie** [comment]
The K_1 to K_4 are pre-generated, I re-upload it as the file 'motion_kernels.mat', you can load it and use it to substitute the Gaussian kernel.

**Comment by haydenhs** [comment]
Got it, thanks for the quick reply.
